<?php

namespace Drupal\route_manager\Form;

use Drupal\Core\Database\Connection;
use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Import form: CSV route import + Audit JSON import (two tabs).
 *
 * Route: /admin/route-manager/import
 */
class ImportForm extends FormBase {

  public function __construct(
    protected Connection $database,
  ) {}

  public static function create(ContainerInterface $container): static {
    return new static(
      $container->get('database'),
    );
  }

  public function getFormId(): string {
    return 'route_manager_import_form';
  }

  public function buildForm(array $form, FormStateInterface $form_state): array {
    $form['#attributes']['enctype'] = 'multipart/form-data';

    $form['tabs'] = [
      '#type' => 'vertical_tabs',
    ];

    // ---- CSV Import tab ----
    $form['csv_tab'] = [
      '#type' => 'details',
      '#title' => $this->t('CSV Import'),
      '#group' => 'tabs',
    ];

    $form['csv_tab']['description'] = [
      '#markup' => '<p>' . $this->t(
        'Upload a CSV with columns: <code>route_name, path, is_public, page_title, meta_title, meta_description, og_title, og_description, og_image, canonical, robots</code>. The <em>path</em> column is required.'
      ) . '</p>',
    ];

    $form['csv_tab']['csv_file'] = [
      '#type' => 'managed_file',
      '#title' => $this->t('CSV file'),
      '#upload_validators' => [
        'file_validate_extensions' => ['csv'],
      ],
      '#upload_location' => 'temporary://',
    ];

    $form['csv_tab']['csv_submit'] = [
      '#type' => 'submit',
      '#value' => $this->t('Import CSV'),
      '#submit' => ['::importCsv'],
      '#validate' => ['::validateCsv'],
    ];

    // ---- Audit JSON Import tab ----
    $form['json_tab'] = [
      '#type' => 'details',
      '#title' => $this->t('Audit JSON Import'),
      '#group' => 'tabs',
    ];

    $form['json_tab']['json_description'] = [
      '#markup' => '<p>' . $this->t(
        'Upload the <code>audit_results.json</code> generated by the Python auditor script. Results will be stored in <code>route_manager_audit</code>.'
      ) . '</p>',
    ];

    $form['json_tab']['json_file'] = [
      '#type' => 'managed_file',
      '#title' => $this->t('audit_results.json'),
      '#upload_validators' => [
        'file_validate_extensions' => ['json'],
      ],
      '#upload_location' => 'temporary://',
    ];

    $form['json_tab']['json_submit'] = [
      '#type' => 'submit',
      '#value' => $this->t('Import Audit JSON'),
      '#submit' => ['::importJson'],
      '#validate' => ['::validateJson'],
    ];

    $form['back'] = [
      '#type' => 'link',
      '#title' => $this->t('← Back to Route Manager'),
      '#url' => Url::fromRoute('route_manager.admin_listing'),
    ];

    return $form;
  }

  // ---------------------------------------------------------------------------
  // CSV
  // ---------------------------------------------------------------------------

  public function validateCsv(array &$form, FormStateInterface $form_state): void {
    $fids = $form_state->getValue('csv_file');
    if (empty($fids)) {
      $form_state->setErrorByName('csv_file', $this->t('Please upload a CSV file.'));
    }
  }

  public function importCsv(array &$form, FormStateInterface $form_state): void {
    $fids = $form_state->getValue('csv_file');
    if (empty($fids)) {
      return;
    }

    $file = $this->entityTypeManager()->getStorage('file')->load(reset($fids));
    if (!$file) {
      $this->messenger()->addError($this->t('Could not load uploaded file.'));
      return;
    }

    $path = \Drupal::service('file_system')->realpath($file->getFileUri());
    $handle = fopen($path, 'r');
    if (!$handle) {
      $this->messenger()->addError($this->t('Could not open CSV file.'));
      return;
    }

    $headers = fgetcsv($handle);
    if (!$headers) {
      $this->messenger()->addError($this->t('CSV file is empty.'));
      fclose($handle);
      return;
    }

    $headers = array_map('trim', $headers);
    $required = ['path'];
    foreach ($required as $col) {
      if (!in_array($col, $headers, TRUE)) {
        $this->messenger()->addError($this->t('CSV missing required column: @col', ['@col' => $col]));
        fclose($handle);
        return;
      }
    }

    $imported = 0;
    $errors = 0;
    $row_num = 1;

    while (($row = fgetcsv($handle)) !== FALSE) {
      $row_num++;
      $data = array_combine($headers, $row);
      if ($data === FALSE) {
        $this->messenger()->addWarning($this->t('Row @n: column count mismatch, skipped.', ['@n' => $row_num]));
        $errors++;
        continue;
      }

      $route_path = trim($data['path'] ?? '');
      if ($route_path === '') {
        $this->messenger()->addWarning($this->t('Row @n: empty path, skipped.', ['@n' => $row_num]));
        $errors++;
        continue;
      }

      // Build metatag_overrides.
      $meta = array_filter([
        'title' => $data['meta_title'] ?? '',
        'description' => $data['meta_description'] ?? '',
        'canonical' => $data['canonical'] ?? '',
        'robots' => $data['robots'] ?? '',
        'og:title' => $data['og_title'] ?? '',
        'og:description' => $data['og_description'] ?? '',
        'og:image' => $data['og_image'] ?? '',
      ], fn($v) => $v !== '');

      $is_public_raw = trim($data['is_public'] ?? '');
      $is_public = ($is_public_raw === '') ? NULL : (int) $is_public_raw;

      $fields = [
        'path' => $route_path,
        'route_name' => trim($data['route_name'] ?? ''),
        'is_public' => $is_public,
        'page_title_override' => trim($data['page_title'] ?? '') ?: NULL,
        'metatag_overrides' => $meta ? serialize($meta) : NULL,
        'updated' => time(),
      ];

      $existing = $this->database->select('route_manager_settings', 'rms')
        ->fields('rms', ['id'])
        ->condition('path', $route_path)
        ->execute()
        ->fetchField();

      if ($existing) {
        $this->database->update('route_manager_settings')
          ->fields($fields)
          ->condition('id', $existing)
          ->execute();
      }
      else {
        $this->database->insert('route_manager_settings')
          ->fields($fields)
          ->execute();
      }

      $imported++;
    }

    fclose($handle);

    // Delete the temporary file.
    $file->delete();

    $this->messenger()->addStatus($this->t(
      'CSV import complete: @imported rows imported, @errors rows skipped.',
      ['@imported' => $imported, '@errors' => $errors]
    ));
  }

  // ---------------------------------------------------------------------------
  // Audit JSON
  // ---------------------------------------------------------------------------

  public function validateJson(array &$form, FormStateInterface $form_state): void {
    $fids = $form_state->getValue('json_file');
    if (empty($fids)) {
      $form_state->setErrorByName('json_file', $this->t('Please upload a JSON file.'));
    }
  }

  public function importJson(array &$form, FormStateInterface $form_state): void {
    $fids = $form_state->getValue('json_file');
    if (empty($fids)) {
      return;
    }

    $file = $this->entityTypeManager()->getStorage('file')->load(reset($fids));
    if (!$file) {
      $this->messenger()->addError($this->t('Could not load uploaded file.'));
      return;
    }

    $path = \Drupal::service('file_system')->realpath($file->getFileUri());
    $raw = file_get_contents($path);
    $pages = json_decode($raw, TRUE);

    if (!is_array($pages)) {
      $this->messenger()->addError($this->t('Invalid JSON file.'));
      $file->delete();
      return;
    }

    $imported = 0;
    $js_error_total = 0;
    $responsive_total = 0;
    $now = time();

    foreach ($pages as $page) {
      if (!isset($page['url'])) {
        continue;
      }

      $page_path = $page['url'];
      $errors = $page['errors'] ?? [];
      $responsive = $page['responsive_issues'] ?? [];

      $js_error_total += count($errors);
      $responsive_total += count($responsive);

      $fields = [
        'path' => $page_path,
        'audit_date' => $now,
        'load_time_ms' => isset($page['load_time_ms']) ? (int) $page['load_time_ms'] : NULL,
        'ttfb_ms' => isset($page['ttfb_ms']) ? (int) $page['ttfb_ms'] : NULL,
        'request_count' => isset($page['request_count']) ? (int) $page['request_count'] : NULL,
        'total_bytes' => isset($page['total_bytes']) ? (int) $page['total_bytes'] : NULL,
        'seo_data' => json_encode($page['seo'] ?? []),
        'errors' => json_encode($errors),
        'responsive_issues' => json_encode($responsive),
        'comparison_data' => json_encode($page['live_comparison'] ?? NULL),
        'status_code' => isset($page['status_code']) ? (int) $page['status_code'] : NULL,
      ];

      // Upsert: replace existing entry for this path (keep most recent).
      $existing = $this->database->select('route_manager_audit', 'a')
        ->fields('a', ['id'])
        ->condition('path', $page_path)
        ->execute()
        ->fetchField();

      if ($existing) {
        $this->database->update('route_manager_audit')
          ->fields($fields)
          ->condition('id', $existing)
          ->execute();
      }
      else {
        $this->database->insert('route_manager_audit')
          ->fields($fields)
          ->execute();
      }

      $imported++;
    }

    $file->delete();

    $this->messenger()->addStatus($this->t(
      'Audit JSON imported: @pages pages, @errors JS errors, @responsive responsive issues.',
      [
        '@pages' => $imported,
        '@errors' => $js_error_total,
        '@responsive' => $responsive_total,
      ]
    ));
  }

  /**
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state): void {
    // Individual submit handlers handle the tabs; this is a no-op fallback.
  }

}
